### ISSUE TITLE
Check gasPrice in buildTransaction

### ISSUE THREAD

**Issue by SukiCZ** [crowd-tools/CrowdClick#24]
this part needs to be checked

_Originally posted by @RiccardoBiosas in https://github.com/crowd-tools/CrowdClick/pull/21#discussion_r607289616_

**Comment by RiccardoBiosas** [comment]
fixed on commit https://github.com/crowd-tools/CrowdClick/commit/6b16b9b7ec330f70134594bc731794c93cb7a84e
